
package xx.mx.uv.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FacturaPortType", targetNamespace = "t4is.uv.mx/factura")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FacturaPortType {


    /**
     * 
     * @param crearFacturaRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.CrearFacturaResponse
     */
    @WebMethod(action = "crearFactura")
    @WebResult(name = "CrearFacturaResponse", targetNamespace = "t4is.uv.mx/factura", partName = "CrearFacturaResponse")
    public CrearFacturaResponse crearFactura(
        @WebParam(name = "CrearFacturaRequest", targetNamespace = "t4is.uv.mx/factura", partName = "CrearFacturaRequest")
        CrearFacturaRequest crearFacturaRequest);

    /**
     * 
     * @param consultarFacturaRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.ConsultarFacturaResponse
     */
    @WebMethod(action = "consultarFactura")
    @WebResult(name = "ConsultarFacturaResponse", targetNamespace = "t4is.uv.mx/factura", partName = "ConsultarFacturaResponse")
    public ConsultarFacturaResponse consultarFactura(
        @WebParam(name = "ConsultarFacturaRequest", targetNamespace = "t4is.uv.mx/factura", partName = "ConsultarFacturaRequest")
        ConsultarFacturaRequest consultarFacturaRequest);

}
